CREATE DATABASE TrackAidDB;
GO
USE TrackAidDB;
GO
CREATE TABLE Companies (
  CompanyID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  Name NVARCHAR(255) NOT NULL,
  Nit NVARCHAR(50) UNIQUE NOT NULL,
  IsActive BIT DEFAULT 1
);
CREATE TABLE Persons (
  PersonID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  FirstName NVARCHAR(100) NOT NULL,
  LastName NVARCHAR(100) NOT NULL,
  DocumentNumber NVARCHAR(50) NOT NULL,
  IsActive BIT DEFAULT 1
);
CREATE TABLE Users (
  UserID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  PersonID UNIQUEIDENTIFIER REFERENCES Persons(PersonID),
  CompanyID UNIQUEIDENTIFIER REFERENCES Companies(CompanyID),
  Email NVARCHAR(255) UNIQUE NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  IsActive BIT DEFAULT 1,
  CreatedAt DATETIME DEFAULT GETDATE()
);
CREATE TABLE Roles (
  RoleID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  RoleName NVARCHAR(50) NOT NULL,
  Description NVARCHAR(MAX),
  IsActive BIT DEFAULT 1
);
CREATE TABLE Permissions (
  PermissionID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  PermissionKey NVARCHAR(100) NOT NULL,
  IsActive BIT DEFAULT 1
);
CREATE TABLE RolePermissions (
  RoleID UNIQUEIDENTIFIER REFERENCES Roles(RoleID),
  PermissionID UNIQUEIDENTIFIER REFERENCES Permissions(PermissionID),
  IsActive BIT DEFAULT 1,
  PRIMARY KEY (RoleID, PermissionID)
);
CREATE TABLE UserRoles (
  UserID UNIQUEIDENTIFIER REFERENCES Users(UserID),
  RoleID UNIQUEIDENTIFIER REFERENCES Roles(RoleID),
  IsActive BIT DEFAULT 1,
  PRIMARY KEY (UserID, RoleID)
);
CREATE TABLE Locations (
  LocationID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  UserID UNIQUEIDENTIFIER REFERENCES Users(UserID),
  Address NVARCHAR(255),
  City NVARCHAR(100),
  State_Province NVARCHAR(100),
  Country NVARCHAR(100),
  IsActive BIT DEFAULT 1
);
CREATE TABLE Orders (
  OrderID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  UserID UNIQUEIDENTIFIER REFERENCES Users(UserID),
  LocationID UNIQUEIDENTIFIER REFERENCES Locations(LocationID),
  CompanyID UNIQUEIDENTIFIER REFERENCES Companies(CompanyID),
  OrderDate DATETIME DEFAULT GETDATE(),
  TotalAmount DECIMAL(18, 2),
  CurrentStatus NVARCHAR(50),
  IsActive BIT DEFAULT 1
);
CREATE TABLE OrderHistory (
  HistoryID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  OrderID UNIQUEIDENTIFIER REFERENCES Orders(OrderID),
  Status NVARCHAR(50),
  LocationDetail NVARCHAR(255),
  ChangeDate DATETIME DEFAULT GETDATE(),
  IsActive BIT DEFAULT 1
);
CREATE TABLE SupportCases (
  CaseID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  OrderID UNIQUEIDENTIFIER NULL REFERENCES Orders(OrderID),
  UserID UNIQUEIDENTIFIER REFERENCES Users(UserID),
  AssignedTo UNIQUEIDENTIFIER NULL REFERENCES Users(UserID),
  CaseType NVARCHAR(50),
  Status NVARCHAR(50),
  Priority NVARCHAR(50),
  IsActive BIT DEFAULT 1,
  CreatedAt DATETIME DEFAULT GETDATE()
);
CREATE TABLE CaseHistory (
  LogID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  CaseID UNIQUEIDENTIFIER REFERENCES SupportCases(CaseID),
  Status NVARCHAR(50),
  Comment NVARCHAR(MAX),
  UpdatedBy UNIQUEIDENTIFIER REFERENCES Users(UserID),
  IsActive BIT DEFAULT 1,
  UpdatedAt DATETIME DEFAULT GETDATE()
);
CREATE TABLE ChatSessions (
  SessionID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  CaseID UNIQUEIDENTIFIER REFERENCES SupportCases(CaseID),
  IsActive BIT DEFAULT 1,
  StartTime DATETIME DEFAULT GETDATE(),
  EndTime DATETIME NULL
);
CREATE TABLE SystemParameters (
  ParamID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  KeyName NVARCHAR(100) UNIQUE NOT NULL,
  Value NVARCHAR(255),
  IsActive BIT DEFAULT 1
);
GO
